OdeToFood/OdeToFood/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OdeToFood.Models;

namespace OdeToFood.Controllers
{
    public class RestaurantController : Controller
    {
        private IOdeToFoodDb db;

        public RestaurantController()
        {
            db = new OdeToFoodDb();
        }

        public RestaurantController(IOdeToFoodDb pDb)
        {
            db = pDb;
        }

        // GET: /Restaurant/
        public ActionResult Index()
        {
            return View(db.Query<Restaurant>().ToList());
        }

        // GET: /Restaurant/Create
        [Authorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Restaurant/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles="admin")]
        public ActionResult Create(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Add(restaurant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(restaurant);
        }

        // GET: /Restaurant/Edit/5
        public ActionResult Edit(int id = 0)
        {
            Restaurant restaurant = db.Find<Restaurant>(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: /Restaurant/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                db.Update(restaurant);
                //before: db.Entry(restaurant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(restaurant);
        }

        // GET: /Restaurant/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Restaurant restaurant = db.Find<Restaurant>(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: /Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Find<Restaurant>(id);
            db.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OdeToFood/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Meine ASP.NET MVC-Anwendung</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @*@Styles.Render("~/Content/themes/base/css")*@
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Ihr Logo hier einfügen", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Startseite", "Index", "Home")</li>
                            <li>@Html.ActionLink("Info", "About", "Home")</li>
                            <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Restaurants", "Index", "Restaurant")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Meine ASP.NET MVC-Anwendung</p>
                </div>
            </div>
        </footer>

        @*@Scripts.Render("~/bundles/jquery")*@
        @Scripts.Render("~/bundles/otf")
        @RenderSection("scripts", required: false)
    </body>
</html>